In [1]:
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [18]:
# Load Dataset
data = pd.read_csv("dataset.csv")
text_column = "content_article"
print("Jumlah data:", len(data))

print(data.head())

Jumlah data: 3376
  date_publication media_source  \
0       2026-01-01       Kontan
1       2026-01-01       Kontan
2       2026-01-01       Kontan
3       2026-01-01       Kontan
4       2026-01-01       Kontan

                                       title_article  \
0  Harga Emas Antam Hari Ini (28/3) Naik Rp 27.00...
1  Kejagung Tetapkan Samin Tan Tersangka, Ini Kas...
2  Asing Net Sell Rp 20,38 Triliun, Cek Saham yan...
3                          Berburu Emas di Pagi Buta
4  Hampir Rampung, ESDM Restui RKAB Batubara 580 ...

                                     content_article  \
0  Reporter: Noverius Laoli | Editor: Noverius La...
1  Reporter: kompas.com | Editor: Noverius Laoli ...
2  Reporter: Noverius Laoli | Editor: Noverius La...
3                      Format Non-Text/Gagal Ekstrak
4  Reporter: Sabrina Rhamadanty | Editor: Ignatia...

                                         url_article sentiment_label  \
0  https://investasi.kontan.co.id/news/harga-emas...          NETRAL
1  https://nasional.kontan.co.id/news/kejagung-te...          NETRAL
2  https://investasi.kontan.co.id/news/asing-net-...          NETRAL
3  https://insight.kontan.co.id/news/berburu-emas...          NETRAL
4  https://industri.kontan.co.id/news/hampir-ramp...          NETRAL

   polarity_score  ai_confidence
0             0.0         0.9178
1             0.0         0.9755
2             0.0         0.9794
3             0.0         0.0000
4             0.0         0.9716

In [17]:
# Sentence Segmentation
text = "Saya belajar NLP. NLP sangat menarik. Saya ingin menjadi NLP Engineer."

sentences = sent_tokenize(text, language='english')  # Ganti 'english' dengan bahasa yang sesuai jika diperlukan

for sentence in sentences:
    print(sentence)

Saya belajar NLP.
NLP sangat menarik.
Saya ingin menjadi NLP Engineer.

In [5]:
#Word Tokenization
from nltk.tokenize import word_tokenize

text = "Saya belajar Natural Language Processing."

tokens = word_tokenize(text)

print(tokens)

['Saya', 'belajar', 'Natural', 'Language', 'Processing', '.']

In [8]:
#Character Tokenization
text = "NLP"

characters = list(text)

print(characters)

['N', 'L', 'P']

In [9]:
# Tokenization Dataset
data["tokens"] = data[text_column].astype(str).apply(word_tokenize)

data[[text_column, "tokens"]].head()

#Menghitung jumlah token per dokumen
data["jumlah_token"] = data["tokens"].apply(len)
data["jumlah_token"].describe()

count    3376.000000
mean      455.390995
std       207.708907
min         3.000000
25%       320.000000
50%       427.500000
75%       550.000000
max      1735.000000
Name: jumlah_token, dtype: float64

In [10]:
#Membandingkan Kata dan Token
data["jumlah_kata"] = data[text_column].astype(str).apply(lambda x: len(x.split()))
data["jumlah_token"] = data["tokens"].apply(len)
data[["jumlah_kata", "jumlah_token"]].describe()

       jumlah_kata  jumlah_token
count  3376.000000   3376.000000
mean    383.772512    455.390995
std     175.876288    207.708907
min       3.000000      3.000000
25%     268.000000    320.000000
50%     361.000000    427.500000
75%     463.000000    550.000000
max    1438.000000   1735.000000

In [21]:
#Eksperimen Tokenisasi
texts = [
    "Saya suka produk ini.",
    "Bagus banget!!!",
    "Tidak bagus...",
    "Harga Rp50.000.",
    "email@example.com",
    "https://example.com",
    "yg bagus bgt sih",
    "aku udah beli nih kak"
]

for text in texts:
    print("TEXT :", text)
    print("TOKEN:", word_tokenize(text))
    print()

TEXT : Saya suka produk ini.
TOKEN: ['Saya', 'suka', 'produk', 'ini', '.']

TEXT : Bagus banget!!!
TOKEN: ['Bagus', 'banget', '!', '!', '!']

TEXT : Tidak bagus...
TOKEN: ['Tidak', 'bagus', '...']

TEXT : Harga Rp50.000.
TOKEN: ['Harga', 'Rp50.000', '.']

TEXT : email@example.com
TOKEN: ['email', '@', 'example.com']

TEXT : https://example.com
TOKEN: ['https', ':', '//example.com']

TEXT : yg bagus bgt sih
TOKEN: ['yg', 'bagus', 'bgt', 'sih']

TEXT : aku udah beli nih kak
TOKEN: ['aku', 'udah', 'beli', 'nih', 'kak']

In [23]:
# Perbandingan Tokenizer
import pandas as pd
import nltk
import spacy
from nltk.tokenize import word_tokenize

# Load model multilingual
nlp = spacy.load("xx_ent_wiki_sm")

# Daftar teks untuk dibandingkan
teks_list = [
    "Saya belajar NLP.",
    "Bagus banget!!!",
    "Harga Rp50.000"
]

# Membandingkan hasil tokenizer
hasil = []

for teks in teks_list:
    nltk_tokens = word_tokenize(teks)
    split_tokens = teks.split()
    doc = nlp(teks)
    spacy_tokens = [token.text for token in doc]

    hasil.append({
        "Teks": teks,
        "NLTK word_tokenize": str(nltk_tokens),
        "split()": str(split_tokens),
        "spaCy": str(spacy_tokens)
    })

# Membuat tabel perbandingan
tabel_perbandingan = pd.DataFrame(hasil)

tabel_perbandingan

,Teks,NLTK word_tokenize,split(),spaCy
0,Saya belajar NLP.,"['Saya', 'belajar', 'NLP', '.']","['Saya', 'belajar', 'NLP.']","['Saya', 'belajar', 'NLP', '.']"
1,Bagus banget!!!,"['Bagus', 'banget', '!', '!', '!']","['Bagus', 'banget!!!']","['Bagus', 'banget', '!', '!', '!']"
2,Harga Rp50.000,"['Harga', 'Rp50.000']","['Harga', 'Rp50.000']","['Harga', 'Rp50.000']"